const cats = [
{  id: "1",
    name: 'Barcelona',
    img: 'https://i.ibb.co/VV6xtTV/IMG-290-A1-B353324-3.webp',
    avail: 'Not available'
},
{  id: "2",
    name: 'Many',
    img: "https://i.ibb.co/NYcYrm5/IMG-0620.webp",
    avail: 'Not available'
},
{  id: "3",
    name: 'Fluff',
    img: "https://i.ibb.co/Lhm6gVL/cat11.webp",
    avail: 'Not available'
},
{  id: "4",
    name: 'Marble girl',
    img: "https://i.ibb.co/vkJdZ7V/kitty.webp",
    avail: 'Not available'
},
{  id: "5",
    name: 'Lilac boy and girl',
    img: "https://i.ibb.co/F3XJTKC/cat3.webp",
    avail: 'available'
},
{  id: "6",
    name: 'Roxy',
    img: "https://i.ibb.co/L6r6Rd1/cat1.webp",
    avail: 'Not available'
},
{  id: "7",
    name: 'The Three Catsketeers',
    img: "https://i.ibb.co/0Q40zP6/cat19.webp",
    avail: 'Not available'
},
{  id: "8",
    name: 'Mommy and baby',
    img: "https://i.ibb.co/Pjv7Szx/cat15.webp",
    avail: 'Not available'
},
{  id: "9",
    name: 'The cat band',
    img: "https://i.ibb.co/TvThqqQ/cat9.webp",
    avail: 'available'
},
{  id: "10",
    name: 'Cream tabby boy',
    img: "https://i.ibb.co/wyX67LM/c7.webp",
    avail: 'Not available'
},
{  id: "11",
    name: 'Chocolate and Lilac',
    img: "https://i.ibb.co/4gSQ66M/cat2.webp",
    avail: 'available'
},
{  id: "12",
    name: 'Babies',
    img: "https://i.ibb.co/LYkYZ3t/IMG-8318.webp",
},
{  id: "13",
    name: 'Babies',
    img: "https://i.ibb.co/Ry67cRh/IMG-8274.webp",
},
{  id: "14",
    name: 'Babies',
    img: "https://i.ibb.co/6DQXRfT/IMG-8066.webp",
},
{  id: "15",
    name: 'Daddy',
    img: "https://i.ibb.co/BztS4c3/IMG-0932.webp",
},
{  id: "16",
    name: 'Babies',
    img: "https://i.ibb.co/r08rx2r/IMG-0637.webp",
},
{  id: "17",
    name: 'Babies',
    img: "https://i.ibb.co/mhPjfS0/IMG-290-A1-B353324-7.webp",
},
{  id: "18",
    name: 'Babies',
    img: "https://i.ibb.co/TKdw4MQ/IMG-290-A1-B353324-5.webp",
},
{  id: "19",
    name: 'Babies',
    img: "https://i.ibb.co/hDK79Vn/cat10.webp",
},
{  id: "20",
    name: 'Babies',
    img: "https://i.ibb.co/d6fwYyS/cat8.webp",
},
{  id: "21",
    name: 'Roxy',
    img: "https://i.ibb.co/zGscFgY/cat6.webp",
},
{  id: "22",
    name: 'Basya',
    img: "https://i.ibb.co/qpjxn4D/c38.webp",
},
{  id: "23",
    name: 'Babies',
    img: "https://i.ibb.co/82fbnfj/cat7.webp",
},
{  id: "24",
    name: 'Basya and Roxy',
    img: "https://i.ibb.co/GtWMX4p/c33.webp",
},
{  id: "25",
    name: 'Basya',
    img: "https://i.ibb.co/qpjxn4D/c38.webp",
},
{  id: "26",
    name: 'Babies',
    img: "https://i.ibb.co/TDfptxg/c29.webp",
},
{  id: "27",
    name: 'Babies',
    img: "https://i.ibb.co/tBpShND/c24.webp",
},
{  id: "28",
    name: 'Babies',
    img: "https://i.ibb.co/Q93hF4x/c12.webp",
},


];
export default cats;