import {c7, c12, c24, c28, c29, c33, c38, cat1, cat2, cat3, cat4, cat6, cat7, cat8, cat9, cat10, cat11, cat19, kitty, basya, kb, k1,many, k2, many2, k3, k4, k5 } from '../images';
const cats = [
{  id: "1",
    name: 'Barcelona',
    img: basya,
    avail: 'Not available'
},
{  id: "2",
    name: 'Many',
    img: many,
    avail: 'Not available'
},
{  id: "3",
    name: 'Fluff',
    img: cat11,
    avail: 'Not available'
},
{  id: "4",
    name: 'Marble girl',
    img: kitty,
    avail: 'Not available'
},
{  id: "5",
    name: 'Lilac boy and girl',
    img: cat3,
    avail: 'available'
},
{  id: "6",
    name: 'Roxy',
    img: cat1,
    avail: 'Not available'
},
{  id: "7",
    name: 'The Three Catsketeers',
    img: cat19,
    avail: 'Not available'
},
{  id: "8",
    name: 'Mommy and baby',
    img: "https://i.ibb.co/Pjv7Szx/cat15.webp",
    avail: 'Not available'
},
{  id: "9",
    name: 'The cat band',
    img: cat9,
    avail: 'available'
},
{  id: "10",
    name: 'Cream tabby boy',
    img: c7,
    avail: 'Not available'
},
{  id: "11",
    name: 'Chocolate and Lilac',
    img: cat2,
    avail: 'available'
},
{  id: "12",
    name: 'Babies',
    img: k5,
},
{  id: "13",
    name: 'Babies',
    img: k4,
},
{  id: "14",
    name: 'Babies',
    img: k3,
},
{  id: "15",
    name: 'Daddy',
    img: many2,
},
{  id: "16",
    name: 'Babies',
    img: k2,
},
{  id: "17",
    name: 'Babies',
    img: k1,
},
{  id: "18",
    name: 'Babies',
    img: kb,
},
{  id: "19",
    name: 'Babies',
    img: cat10,
},
{  id: "20",
    name: 'Babies',
    img: cat8,
},
{  id: "21",
    name: 'Roxy',
    img: cat6,
},
{  id: "22",
    name: 'Basya',
    img: c38,
},
{  id: "23",
    name: 'Babies',
    img: c7,
},
{  id: "24",
    name: 'Basya and Roxy',
    img: c33,
},
{  id: "25",
    name: 'Basya',
    img: cat4,
},
{  id: "26",
    name: 'Babies',
    img: c29,
},
{  id: "27",
    name: 'Babies',
    img: c24,
},
{  id: "28",
    name: 'Babies',
    img: c12,
},
{  id: "29",
    name: 'Babies',
    img: c28,
},
];

export default cats;