
const cats = [
{  id: "1",
    name: 'Barcelona',
    img: "https://i.ibb.co/d78d61p/c36.webp",
    avail: 'Not available'
},
{  id: "2",
    name: 'Many',
    img: "https://i.ibb.co/WcX3sZ7/Many.webp",
    avail: 'Not available'
},
{  id: "3",
    name: 'Fluff',
    img: "https://i.ibb.co/5LRpXD3/cat11.webp",
    avail: 'Not available'
},
{  id: "4",
    name: 'Marble girl',
    img: "https://i.ibb.co/zGfhjkH/kitty.webp",
    avail: 'Not available'
},
{  id: "5",
    name: 'Lilac boy and girl',
    img: "https://i.ibb.co/KynrN0j/cat3.webp",
    avail: 'available'
},
{  id: "6",
    name: 'Roxy',
    img: "https://i.ibb.co/VTXmBh9/cat6.webp",
    avail: 'Not available'
},
{  id: "7",
    name: 'The Three Catsketeers',
    img: "https://i.ibb.co/RYCcm7j/cat19.webp",
    avail: 'Not available'
},
{  id: "8",
    name: 'Mommy and baby',
    img: "https://i.ibb.co/m5KLVxL/cat4.webp",
    avail: 'Not available'
},
{  id: "9",
    name: 'The cat band',
    img: "https://i.ibb.co/FhPPvT8/cat9.webp",
    avail: 'available'
},
{  id: "10",
    name: 'Cream tabby boy',
    img: "https://i.ibb.co/VBmDnhv/c7.webp",
    avail: 'Not available'
},
{  id: "11",
    name: 'Chocolate and Lilac',
    img: "https://i.ibb.co/ch5Dgz5/cat2.webp",
    avail: 'available'
},
{  id: "12",
    name: 'Babies',
    img: "https://i.ibb.co/8Nnhfzf/cat8.webp",
},
{  id: "13",
    name: 'Babies',
    img: "https://i.ibb.co/TLW7SbT/lilac-Male.webp",
},
{  id: "14",
    name: 'Babies',
    img: "https://i.ibb.co/JQVNpwL/baby.webp",
},
{  id: "15",
    name: 'Daddy',
    img: "https://i.ibb.co/52cQp3X/Many2.webp",
},
{  id: "16",
    name: 'Babies',
    img: "https://i.ibb.co/SnWLS7m/c2.webp",
},
{  id: "17",
    name: 'Babies',
    img: "https://i.ibb.co/KxqD861/lilac-Female.webp",
},
{  id: "18",
    name: 'Babies',
    img: "https://i.ibb.co/RHWbk5Z/c29.webp",
},
{  id: "19",
    name: 'Babies',
    img: "https://i.ibb.co/9tW8tkQ/cat10.webp",
},
{  id: "20",
    name: 'Babies',
    img: "https://i.ibb.co/2SWrh9t/c100.webp",
},
{  id: "21",
    name: 'Roxy',
    img: "https://i.ibb.co/JzXy7ph/cat1.webp",
},
{  id: "22",
    name: 'Basya',
    img: "https://i.ibb.co/M2nmkvM/c38.webp",
},
{  id: "23",
    name: 'Babies',
    img: "https://i.ibb.co/zhcy0JP/c.webp",
},
{  id: "24",
    name: 'Basya and I',
    img: "https://i.ibb.co/YpvfZnn/c4.webp",
},
{  id: "25",
    name: 'Basya',
    img: "https://i.ibb.co/RQrYdXD/c38.webp",
},
{  id: "26",
    name: 'Babies',
    img: "https://i.ibb.co/RBmK7CQ/c12.webp",
},
{  id: "27",
    name: 'Babies',
    img: "https://i.ibb.co/qdZS27k/cat7.webp",
},
{  id: "28",
    name: 'Babies',
    img: "https://i.ibb.co/gJpDtBw/c3.webp",
},
{  id: "29",
    name: 'Babies',
    img: "https://i.ibb.co/CvPh6S8/baby2.webp",
},
];

export default cats;