const cats = [
{  id: "1",
    name: 'Barcelona',
    img: 'https://i.ibb.co/DC16Twx/IMG-290-A1-B353324-3.jpg',
    avail: 'Not available'
},
{  id: "2",
    name: 'Many',
    img: "https://i.ibb.co/jwZbzHC/IMG-0620-2.jpg",
    avail: 'Not available'
},
{  id: "3",
    name: 'Fluff',
    img: "https://i.ibb.co/GJ63CXT/cat11.jpg",
    avail: 'Not available'
},
{  id: "4",
    name: 'Marble girl',
    img: "https://i.ibb.co/p4T6pHH/6731-ABEE-8-FE7-4525-A495-05-A819831455.jpg",
    avail: 'Not available'
},
{  id: "5",
    name: 'Lilac boy and girl',
    img: "https://i.ibb.co/6mcfHkK/cat3.jpg",
    avail: 'available'
},
{  id: "6",
    name: 'Roxy',
    img: "https://i.ibb.co/Jx06dcJ/cat1.jpg",
    avail: 'Not available'
},
{  id: "7",
    name: 'The Three Catsketeers',
    img: "https://i.ibb.co/yfT23jh/cat19.jpg",
    avail: 'Not available'
},
{  id: "8",
    name: 'Mommy and baby',
    img: "https://i.ibb.co/B6XdnjS/cat15.jpg",
    avail: 'Not available'
},
{  id: "9",
    name: 'The cat band',
    img: "https://i.ibb.co/n78SPkw/cat9.jpg",
    avail: 'available'
},
{  id: "10",
    name: 'Cream tabby boy',
    img: "https://i.ibb.co/ZN56HVV/cat7.jpg",
    avail: 'Not available'
},
{  id: "11",
    name: 'Chocolate and Lilac',
    img: "https://i.ibb.co/QFJ0w6C/cat2.jpg",
    avail: 'available'
},
{  id: "12",
    name: 'Babies',
    img: "https://i.ibb.co/gFJbBb4/c.jpg",
},
{  id: "13",
    name: 'Babies',
    img: "https://i.ibb.co/FYLdqHv/c1.jpg",
},
{  id: "14",
    name: 'Babies',
    img: "https://i.ibb.co/mNGR3df/c2.jpg",
},
{  id: "15",
    name: 'Babies',
    img: "https://i.ibb.co/68swyLY/c3.jpg",
},
{  id: "16",
    name: 'Babies',
    img: "https://i.ibb.co/4YbssS8/c4.jpg",
},
{  id: "17",
    name: 'Babies',
    img: "https://i.ibb.co/93btncG/c6.jpg",
},
{  id: "18",
    name: 'Babies',
    img: "https://i.ibb.co/qm4xhR8/c7.jpg",
},
{  id: "19",
    name: 'Babies',
    img: "https://i.ibb.co/9GsFHqF/c8.jpg",
},
{  id: "20",
    name: 'Babies',
    img: "https://i.ibb.co/JjQtVWt/c9.jpg",
},
{  id: "21",
    name: 'Roxy',
    img: "https://i.ibb.co/P90zKs5/c10.jpg",
},
{  id: "22",
    name: 'Basya',
    img: "https://i.ibb.co/f1gKhmW/c11.jpg",
},
{  id: "23",
    name: 'Babies',
    img: "https://i.ibb.co/3pnK6hm/c12.jpg",
},
{  id: "24",
    name: 'Basya',
    img: "https://i.ibb.co/L61wwXt/c13.jpg",
},
{  id: "25",
    name: 'Basya',
    img: "https://i.ibb.co/znyQWsv/c15.jpg",
},
{  id: "26",
    name: 'Babies',
    img: "https://i.ibb.co/Rg1JT9k/c18.jpg",
},
{  id: "27",
    name: 'Babies',
    img: "https://i.ibb.co/Nxqydqd/c20.jpg",
},
{  id: "28",
    name: 'Babies',
    img: "https://i.ibb.co/Hx1wzgk/c19.jpg",
},


];
export default cats;